config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static#home'
  get '/home_club', to: 'static#home_club'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ApplicationRecord
  attr_accessor :remember_token

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'You are now logged in'
      redirect_to '/'
    else
      flash[:notice] = 'Obviously something went wrong...'
    end
  end

  def destroy
    log_out
    flash[:success] = 'You\'ve been logged out'
    redirect_to '/'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
    end

    def home_club
        if logged_in? == false
            flash.now[:danger] = 'You\'re not allowed to go there'
            redirect_to '/'
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        user = User.create(first_name: params[:user][:first_name], last_name: params[:user][:last_name], email: params[:user][:email], password: params[:user][:password])
        if user.new_record? == false
            log_in user
            params[:user][:remember_me] == '1' ? remember(user) : forget(user)
            flash[:success] = 'You\'ve successfully been added to the Member List'
            redirect_to '/'
        else
            flash[:danger] = 'We\'re sorry but there is obviously a problem with your registration... Please try agan!'
        end
    end

    def show
        @user = User.find(params[:id])
        if current_user.id != @user.id
            flash[:danger] = 'You\'re not allowed to do this kind of action'
            redirect_to '/'
        end
    end

    def edit
        @user = User.find(params[:id])
        if current_user.id != @user.id
            flash[:danger] = 'You\'re not allowed to do this kind of action'
            redirect_to '/'
        end
    end

    def update
        @user = User.find(params[:id])
        user_params = params.require(:user).permit(:email, :password, :password_confirmation)
        if @user.update_attributes(user_params)
            flash[:success] = 'Account successfully updated!'
            redirect_to '/'
        else
            flash[:danger] = 'We\'re sorry but there is obviously a problem with your registration... Please try agan!'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = 'Account successfully deleted. Hope to see you again!!'
        redirect_to '/'
    end

    def index
        @users = User.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
      end

      def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
      end
end   

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suits Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <%= link_to "The Suits Club", "/", id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", "/" %></li>
            <li><%= link_to "New Member", new_user_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Lounge", "/home_club" %></li>
              <li><%= link_to "Club Members", '/users' %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", "#" %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

   <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
   <% end %>
    <%= yield %>
  </body>

</html>

app/views/users/edit.html.erb
</br>
<h3>Modification de l'utilisateur</h3>
</br>
<div class="formy">
	<%= form_for(@user) do |f| %>
		<div class="form-group">
			<%= f.label 'E-mail' %>
			<%= f.email_field :email, class:"form-control", placeholder:"E-mail" %>
		</div>
		<div class="form-group">
			<%= f.label 'Mot de passe' %>
			<%= f.password_field :password, class:"form-control", placeholder:"Mot de passe" %>
		</div>
		<div class="form-group">
			<%= f.label 'Confirme le mot de passe' %>
			<%= f.password_field :password_confirmation, class:"form-control", placeholder:"Mot de passe" %>
		</div>
		<%= f.submit "Modifier", class:"btn btn-primary" %>
	<% end %>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    </br>
    <h3>Club Members</h3>
    </br>
    <ul>
    <% @users.each do |user| %>
        <li><%= user.first_name %> <%= user.last_name %></li>
    <% end %>
    </ul>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="fr" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title>New Member</title>
	</head>
	<body>
		</br>
			<center>
	      <br><br><br><br><br><br><br><br>
		<h3>Member Subscription</h3>
		</br>
		<div class="formy">
			<%= form_for(:user, url: users_path) do |f| %>
				<div class="form-group">
					<%= f.label 'Enter your First Name' %>
					<%= f.text_field :first_name, class:"form-control", placeholder:"First Name" %>
				</div>
				<div class="form-group">
					<%= f.label 'Enter your Last Name' %>
					<%= f.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
				</div>
				<div class="form-group">
					<%= f.label 'Enter your E-mail' %>
					<%= f.text_field :email, class:"form-control", placeholder:"E-mail" %>
				</div>
				<div class="form-group">
					<%= f.label 'Enter your password' %>
					<%= f.password_field :password, class:"form-control", placeholder:"Password" %>
				</div>
				<div class="form-group">
					<%= f.label :remember_me, class: "checkbox inline" do %>
		        		<%= f.check_box :remember_me %><span>Remember me</span>
		      		<% end %>
				</div>
				<p><%= f.submit "Subscribe", class:"btn btn-primary" %></p>
			<% end %>
		</div>

	</body>
</html>

app/views/users/show.html.erb
</br>
<h3>Ta page d'utilisateur</h3>
</br>
<p>Ton e-mail : <%= @user.email %></p>
<p><%= link_to "Modifier", edit_user_path(current_user), class:"btn btn-primary" %> <%= link_to 'Supprimer', :user, method: :delete , class:"btn btn-primary" %></p>